-- MySQL Script generated by MySQL Workbench
-- 04/28/17 13:18:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbi359591
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbi359591
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbi359591` DEFAULT CHARACTER SET utf8 ;
USE `dbi359591` ;

-- -----------------------------------------------------
-- Table `dbi359591`.`Visitor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbi359591`.`Visitor` ;

CREATE TABLE IF NOT EXISTS `dbi359591`.`Visitor` (
  `idVisitor` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Telephone` INT NOT NULL,
  PRIMARY KEY (`idVisitor`),
  UNIQUE INDEX `idVisitor_UNIQUE` (`idVisitor` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbi359591`.`Event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbi359591`.`Event` ;

CREATE TABLE IF NOT EXISTS `dbi359591`.`Event` (
  `idEvent` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Location` VARCHAR(45) NOT NULL,
  `PriceForEntrance` DOUBLE NULL,
  PRIMARY KEY (`idEvent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbi359591`.`Stand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbi359591`.`Stand` ;

CREATE TABLE IF NOT EXISTS `dbi359591`.`Stand` (
  `idStand` INT NOT NULL AUTO_INCREMENT,
  `Type` ENUM('FoodStand', 'SD') NOT NULL,
  `Location` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idStand`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbi359591`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbi359591`.`Employee` ;

CREATE TABLE IF NOT EXISTS `dbi359591`.`Employee` (
  `idEmployee` INT NOT NULL AUTO_INCREMENT,
  `EmployeeName` VARCHAR(45) NOT NULL,
  `Stand_idStand` INT NOT NULL,
  PRIMARY KEY (`idEmployee`),
  INDEX `fk_Employee_Stand1_idx` (`Stand_idStand` ASC),
  CONSTRAINT `fk_Employee_Stand1`
    FOREIGN KEY (`Stand_idStand`)
    REFERENCES `dbi359591`.`Stand` (`idStand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbi359591`.`Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbi359591`.`Account` ;

CREATE TABLE IF NOT EXISTS `dbi359591`.`Account` (
  `RFID` VARCHAR(45) NOT NULL,
  `EventAccount` DOUBLE NOT NULL,
  `Visitor_idVisitor` INT NOT NULL,
  PRIMARY KEY (`RFID`),
  INDEX `fk_Account_Visitor1_idx` (`Visitor_idVisitor` ASC),
  UNIQUE INDEX `idAccount_UNIQUE` (`RFID` ASC),
  CONSTRAINT `fk_Account_Visitor1`
    FOREIGN KEY (`Visitor_idVisitor`)
    REFERENCES `dbi359591`.`Visitor` (`idVisitor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbi359591`.`Rent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbi359591`.`Rent` ;

CREATE TABLE IF NOT EXISTS `dbi359591`.`Rent` (
  `idRent` INT NOT NULL AUTO_INCREMENT,
  `Date` DATETIME NOT NULL,
  `Employee_idEmployee` INT NOT NULL,
  `Total` DOUBLE NOT NULL,
  `Account_RFID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRent`),
  INDEX `fk_Rent_Employee1_idx` (`Employee_idEmployee` ASC),
  INDEX `fk_Rent_Account1_idx` (`Account_RFID` ASC),
  CONSTRAINT `fk_Rent_Employee1`
    FOREIGN KEY (`Employee_idEmployee`)
    REFERENCES `dbi359591`.`Employee` (`idEmployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rent_Account1`
    FOREIGN KEY (`Account_RFID`)
    REFERENCES `dbi359591`.`Account` (`RFID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbi359591`.`Item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbi359591`.`Item` ;

CREATE TABLE IF NOT EXISTS `dbi359591`.`Item` (
  `idItem` INT NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(45) NOT NULL,
  `UnitPrice` DOUBLE NOT NULL,
  PRIMARY KEY (`idItem`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbi359591`.`PayPal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbi359591`.`PayPal` ;

CREATE TABLE IF NOT EXISTS `dbi359591`.`PayPal` (
  `idPayPal` INT NOT NULL,
  `StartPeriod` DATETIME NOT NULL,
  `EndPEriod` DATETIME NOT NULL,
  `NrOfDeposits` INT NOT NULL,
  PRIMARY KEY (`idPayPal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbi359591`.`Camping`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbi359591`.`Camping` ;

CREATE TABLE IF NOT EXISTS `dbi359591`.`Camping` (
  `idCamping` INT NOT NULL AUTO_INCREMENT,
  `CampingLocation` VARCHAR(45) NOT NULL,
  `PricePerGuest` DOUBLE NOT NULL DEFAULT 20,
  `PriceForOrder` DOUBLE NOT NULL DEFAULT 30,
  `Total` DOUBLE NOT NULL,
  `Account_RFID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCamping`),
  INDEX `fk_Camping_Account1_idx` (`Account_RFID` ASC),
  CONSTRAINT `fk_Camping_Account1`
    FOREIGN KEY (`Account_RFID`)
    REFERENCES `dbi359591`.`Account` (`RFID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbi359591`.`DepositLine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbi359591`.`DepositLine` ;

CREATE TABLE IF NOT EXISTS `dbi359591`.`DepositLine` (
  `idDepositLine` INT NOT NULL,
  `Amount` DOUBLE NOT NULL,
  `PayPal_idPayPal` INT NOT NULL,
  `Visitor_idVisitor` INT NOT NULL,
  PRIMARY KEY (`idDepositLine`, `PayPal_idPayPal`),
  INDEX `fk_DepositLine_PayPal1_idx` (`PayPal_idPayPal` ASC),
  INDEX `fk_DepositLine_Visitor1_idx` (`Visitor_idVisitor` ASC),
  CONSTRAINT `fk_DepositLine_PayPal1`
    FOREIGN KEY (`PayPal_idPayPal`)
    REFERENCES `dbi359591`.`PayPal` (`idPayPal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DepositLine_Visitor1`
    FOREIGN KEY (`Visitor_idVisitor`)
    REFERENCES `dbi359591`.`Visitor` (`idVisitor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbi359591`.`Reservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbi359591`.`Reservation` ;

CREATE TABLE IF NOT EXISTS `dbi359591`.`Reservation` (
  `idReservation` INT NOT NULL AUTO_INCREMENT,
  `ReservationDate` DATETIME NOT NULL,
  `Event_idEvent` INT NOT NULL,
  `HasEnteredEvent` TINYINT(1) NOT NULL,
  `DepositLine_idDepositLine` INT NOT NULL,
  `DepositLine_PayPal_idPayPal` INT NOT NULL,
  PRIMARY KEY (`idReservation`),
  INDEX `fk_Reservation_Event1_idx` (`Event_idEvent` ASC),
  INDEX `fk_Reservation_DepositLine1_idx` (`DepositLine_idDepositLine` ASC, `DepositLine_PayPal_idPayPal` ASC),
  CONSTRAINT `fk_Reservation_Event1`
    FOREIGN KEY (`Event_idEvent`)
    REFERENCES `dbi359591`.`Event` (`idEvent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_DepositLine1`
    FOREIGN KEY (`DepositLine_idDepositLine` , `DepositLine_PayPal_idPayPal`)
    REFERENCES `dbi359591`.`DepositLine` (`idDepositLine` , `PayPal_idPayPal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbi359591`.`Food`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbi359591`.`Food` ;

CREATE TABLE IF NOT EXISTS `dbi359591`.`Food` (
  `idFood` INT NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(45) NOT NULL,
  `UnitPrice` DOUBLE NOT NULL,
  PRIMARY KEY (`idFood`),
  UNIQUE INDEX `idFood_UNIQUE` (`idFood` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbi359591`.`FoodOrder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbi359591`.`FoodOrder` ;

CREATE TABLE IF NOT EXISTS `dbi359591`.`FoodOrder` (
  `idFoodOrder` INT NOT NULL AUTO_INCREMENT,
  `Employee_idEmployee` INT NOT NULL,
  `Date` DATETIME NOT NULL,
  `Total` DOUBLE NOT NULL,
  `Account_RFID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFoodOrder`),
  INDEX `fk_Order_Employee1_idx` (`Employee_idEmployee` ASC),
  INDEX `fk_FoodOrder_Account1_idx` (`Account_RFID` ASC),
  CONSTRAINT `fk_Order_Employee1`
    FOREIGN KEY (`Employee_idEmployee`)
    REFERENCES `dbi359591`.`Employee` (`idEmployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FoodOrder_Account1`
    FOREIGN KEY (`Account_RFID`)
    REFERENCES `dbi359591`.`Account` (`RFID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbi359591`.`OrderLine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbi359591`.`OrderLine` ;

CREATE TABLE IF NOT EXISTS `dbi359591`.`OrderLine` (
  `FoodOrder_idFoodOrder` INT NOT NULL AUTO_INCREMENT,
  `LineNumber` INT NOT NULL,
  `Food_idFood` INT NOT NULL,
  `Quantity` INT NOT NULL,
  `UnitPrice` DOUBLE NOT NULL,
  `ExtendedPrice` DOUBLE NOT NULL,
  PRIMARY KEY (`FoodOrder_idFoodOrder`, `LineNumber`),
  INDEX `fk_OrderLine_Order1_idx` (`FoodOrder_idFoodOrder` ASC),
  INDEX `fk_OrderLine_Food1_idx` (`Food_idFood` ASC),
  CONSTRAINT `fk_OrderLine_Order1`
    FOREIGN KEY (`FoodOrder_idFoodOrder`)
    REFERENCES `dbi359591`.`FoodOrder` (`idFoodOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrderLine_Food1`
    FOREIGN KEY (`Food_idFood`)
    REFERENCES `dbi359591`.`Food` (`idFood`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbi359591`.`ItemReturns`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbi359591`.`ItemReturns` ;

CREATE TABLE IF NOT EXISTS `dbi359591`.`ItemReturns` (
  `idReturns` INT NOT NULL AUTO_INCREMENT,
  `Visitor_idVisitor` INT NOT NULL,
  `DateReturned` DATETIME NOT NULL,
  PRIMARY KEY (`idReturns`),
  INDEX `fk_ItemReturns_Visitor1_idx` (`Visitor_idVisitor` ASC),
  CONSTRAINT `fk_ItemReturns_Visitor1`
    FOREIGN KEY (`Visitor_idVisitor`)
    REFERENCES `dbi359591`.`Visitor` (`idVisitor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbi359591`.`RentLine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbi359591`.`RentLine` ;

CREATE TABLE IF NOT EXISTS `dbi359591`.`RentLine` (
  `Line` INT NOT NULL AUTO_INCREMENT,
  `Rent_idRent` INT NOT NULL,
  `Item_idItem` INT NOT NULL,
  `ItemReturns_idReturns` INT NOT NULL,
  `Qunatity` INT NOT NULL,
  `UnitPrice` DOUBLE NOT NULL,
  `ExtendedPrice` DOUBLE NOT NULL,
  PRIMARY KEY (`Line`, `Rent_idRent`, `ItemReturns_idReturns`),
  INDEX `fk_Rent_has_Item_Rent1_idx` (`Rent_idRent` ASC),
  INDEX `fk_Rent_has_Item_Item1_idx` (`Item_idItem` ASC),
  INDEX `fk_RentLine_ItemReturns1_idx` (`ItemReturns_idReturns` ASC),
  CONSTRAINT `fk_Rent_has_Item_Rent1`
    FOREIGN KEY (`Rent_idRent`)
    REFERENCES `dbi359591`.`Rent` (`idRent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rent_has_Item_Item1`
    FOREIGN KEY (`Item_idItem`)
    REFERENCES `dbi359591`.`Item` (`idItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RentLine_ItemReturns1`
    FOREIGN KEY (`ItemReturns_idReturns`)
    REFERENCES `dbi359591`.`ItemReturns` (`idReturns`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbi359591`.`Guest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbi359591`.`Guest` ;

CREATE TABLE IF NOT EXISTS `dbi359591`.`Guest` (
  `Line` INT NOT NULL AUTO_INCREMENT,
  `Visitor_idVisitor` INT NOT NULL,
  `Camping_idCamping` INT NOT NULL,
  PRIMARY KEY (`Line`, `Camping_idCamping`),
  INDEX `fk_Guest_Visitor1_idx` (`Visitor_idVisitor` ASC),
  INDEX `fk_Guest_Camping1_idx` (`Camping_idCamping` ASC),
  CONSTRAINT `fk_Guest_Visitor1`
    FOREIGN KEY (`Visitor_idVisitor`)
    REFERENCES `dbi359591`.`Visitor` (`idVisitor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Guest_Camping1`
    FOREIGN KEY (`Camping_idCamping`)
    REFERENCES `dbi359591`.`Camping` (`idCamping`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbi359591`.`Entrance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbi359591`.`Entrance` ;

CREATE TABLE IF NOT EXISTS `dbi359591`.`Entrance` (
  `Visitor_idVisitor` INT NOT NULL,
  `Event_idEvent` INT NOT NULL,
  `HasEnteredEvent` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Visitor_idVisitor`, `Event_idEvent`),
  INDEX `fk_Visitor_has_Event_Event1_idx` (`Event_idEvent` ASC),
  INDEX `fk_Visitor_has_Event_Visitor1_idx` (`Visitor_idVisitor` ASC),
  CONSTRAINT `fk_Visitor_has_Event_Visitor1`
    FOREIGN KEY (`Visitor_idVisitor`)
    REFERENCES `dbi359591`.`Visitor` (`idVisitor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visitor_has_Event_Event1`
    FOREIGN KEY (`Event_idEvent`)
    REFERENCES `dbi359591`.`Event` (`idEvent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
